name: Terraform Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: 'Terraform Lint'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Lint
      uses: actions/terraform-lint@v1